### ISSUE TITLE
评论插件样式有问题

### ISSUE THREAD

**Issue by ilovecopy** [laoergege/laoergege-blog#90]
博客地址： https://ilovecopy.github.io/CSNotes/network/011.html#_1-1-6-计算机网络的性能指标

代码片段：https://github.com/ilovecopy/CSNotes/blob/main/docs/.vuepress/config.js
插件：@laoergege/vuepress-plugin-vssue-next-compat

截图：

<img width="333" alt="image" src="https://user-images.githubusercontent.com/58297115/179646615-dabb177e-6222-4a9c-a634-a8a4916ca157.png">

<img width="707" alt="image" src="https://user-images.githubusercontent.com/58297115/179507108-afec9dbc-f65a-4fa3-8181-b517130b094d.png">

**Comment by 1129921824** [comment]
您好，您的样式问题解决了吗
